// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/17/2024, 4:32:35 PM
const configMerger = require("/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/plugins/**/*.{js,ts,mjs}","/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/composables/**/*.{js,ts,mjs}","/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/utils/**/*.{js,ts,mjs}","/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/app.config.{js,ts,mjs}"] }));

module.exports = (() => {const cfg=config;cfg["content"]["23"] = "/Users/prassannopane/Documents/WEBDESIGN_BRAM/portfolioPrassan2/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";cfg["darkMode"] = ["selector","[class~=\"dark-mode\"]"];;return cfg;})()
